---
abstract: ~
author:
  - 'Peter Mayr <at.peter.mayr@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Arduino-Watcher
no_index:
  directory:
    - inc
    - t
requires:
  Device::SerialPort::Arduino: 0
  LWP::UserAgent: 0
  Log::Log4perl: 0
  Moose: 0
  MooseX::Daemonize: 0
  MooseX::Log::Log4perl: 0
  MooseX::Runnable: 0
  Try::Tiny: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
